title = "Aegna"
baseURL = "https://aegnaintis.github.io/"
languageCode = "en"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "A terryfing glimpse into Tom's mind."
  facebook = "https://www.facebook.com/groups/185501178782555/"
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/background.png"
  recent_posts_number = 0
  toc = true





